# P36: Automated test failure fix pipeline
# Reference: Claude Code in Production, Part 4

name: Auto Fix Tests
on:
  workflow_run:
    workflows: ["Run Tests"]
    types: [completed]
jobs:
  auto-fix:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Claude Code
        run: npm install -g @anthropic-ai/claude-code
      - name: Capture test failures
        id: test
        continue-on-error: true
        run: npm test 2>&1 | tee test-output.txt
      - name: Attempt Auto Fix
        if: steps.test.outcome == 'failure'
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bash .github/scripts/auto-fix.sh
